### ISSUE TITLE
Typo in snmp defaults

### ISSUE THREAD

**Issue by eporter82** [robertdebock/ansible-role-snmpd#2]
# Describe the bug

There's a typo in the ```robertdebock.snmpd``` defaults

## Original
```defaults/main.yml```

```
...
snmpd_groups:
  - name: notConfigGroup
    security_model: v1
    security_name: notConfigUser
  - name: NotConfigGroup
    security_model: v2c
    security_name: NotConfigUser
...
```
## Should be
```
snmpd_groups:
  - name: notConfigGroup
    security_model: v1
    security_name: notConfigUser
  - name: notConfigGroup
    security_model: v2c
    security_name: notConfigUser

```
